server:
  host: 127.0.0.1
  port: 5005

template_dir: templates
static_dir: static


secret_key: gKmRu3ivruk6ieFllGo8lUag0NpYY1Pr

app:
  mode: dev

  auth: True
  admin: True

  auto_protect: True
  blacklist: "null"
  whitelist: "null"
  max_fail: 5
  fail_interval: 300
  ban_time: 300

database:
  engine: sqlite
  filename: app.db